//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachments
    {
        public int id { get; set; }
        public string descr { get; set; }
        public string file_path { get; set; }
        public int task_id { get; set; }
        public Nullable<int> cust_id { get; set; }
    }
}
